resources:
- name: phd-ci
  type: git
  source:
    uri: {{phd-ci-uri}}
    branch: {{phd-ci-branch}}
    username: {{phd-ci-repo-username}}
    password: {{phd-ci-repo-password}}

- name: ambari
  type: git
  source:
    uri: {{ambari-uri}}
    branch: {{ambari-branch}}
    private_key: {{private-key}}

- name: docker-image
  type: docker-image
  source:
    email: {{docker-hub-useremail}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-repo}}

- name: ambari-internal-s3-bucket
  type: s3
  source:
    access_key_id: {{ambari-internal-s3-bucket-key-id}}
    secret_access_key: {{ambari-internal-s3-bucket-access-key}}
    bucket: ambari-internal/dev
    region_name: us-west-2
    versioned_file: file.txt

jobs:
- name: build-ambari
  plan:
  - aggregate:
    - get: phd-ci
      trigger: true
    - get: ambari
      trigger: true
  - task: build-ambari-rpms
    priviliged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          username: {{docker-hub-username}}
          password: {{docker-hub-password}}
          repository: {{docker-hub-repo}}
      inputs:
        - name: phd-ci
        - name: ambari
      run:
        path: phd-ci/ambari-ci/jobs/build/scripts/build-ambari4.sh
      outputs:
        - name: build-ambari
  - put: ambari-internal-s3-bucket
    params:
      file: build-ambari/file.txt
