resources:
- name: phd-ci
  type: git
  source:
    uri: {{phd-ci-uri}}
    branch: {{phd-ci-branch}}
    username: {{phd-ci-repo-username}}
    password: {{phd-ci-repo-password}}

- name: ambari
  type: git
  source:
    uri: {{ambari-uri}}
    branch: {{ambari-branch}}
    private_key: {{private-key}}

- name: docker-image
  type: docker-image
  source:
    email: {{docker-hub-useremail}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-repo}}

jobs:
- name: build-ambari
  plan:
  - aggregate:
    - get: phd-ci
      trigger: true
    - get: ambari
      trigger: true
  - aggregate:
    - task: build-ambari-rpms
      priviliged: true
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            username: {{docker-hub-username}}
            password: {{docker-hub-password}}
            repository: {{docker-hub-repo}}
        inputs:
          - name: phd-ci
          - name: ambari
        run:
          path: phd-ci/ambari-ci/jobs/build/scripts/build-ambari3.sh
