resources:
- name: phd-ci
  type: git
  source:
    uri: {{phd-ci-uri}}
    branch: {{phd-ci-branch}}
    username: {{phd-ci-repo-username}}
    password: {{phd-ci-repo-password}}

- name: ambari
  type: git
  source:
    uri: {{ambari-uri}}
    branch: {{ambari-branch}}
    private_key: {{private-key}}

- name: docker-image
  type: docker-image
  source:
    email: {{docker-hub-useremail}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-repo}}

- name: ambari-internal-s3-bucket
  type: s3
  source:
    access_key_id: {{ambari-internal-s3-bucket-key-id}}
    secret_access_key: {{ambari-internal-s3-bucket-access-key}}
    bucket: ambari-concourse-test
    region_name: us-west-2
    versioned_file: AMBARI-trunk-HDP-latest-concourse.tar.gz

jobs:
- name: build-ambari-trunk
  plan:
  - aggregate:
    - get: phd-ci
      trigger: true
    - get: ambari
      trigger: true
  - task: build-ambari-rpms
    priviliged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          username: {{docker-hub-username}}
          password: {{docker-hub-password}}
          repository: {{docker-hub-repo}}
      inputs:
        - name: phd-ci
        - name: ambari
      params:
        SKIP_TEST: -DskipTests
        SKIP_RAT_TEST: -Drat.skip
        AMBARI_BUILD_VERSION: 2.4.0.0-1
        AMBARI_RPM_FOLDER: AMBARI-trunk-HDP-latest-concourse
      run:
        path: phd-ci/scripts/build-ambari.sh
      outputs:
        - name: ambari_artifacts
  - put: ambari-internal-s3-bucket
    params:
      file: ambari_artifacts/AMBARI-trunk-HDP-latest-concourse.tar.gz
